"use client";

import React, { useState, useEffect } from "react";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { GlowText } from "@/components/ui/GlowText";
import { EvidenceCard } from "@/components/ui/EvidenceCard";
import { RiskBadge } from "@/components/ui/RiskBadge";
import { ArrowDown, Check, ShieldCheck, Database, FileText, ExternalLink, Loader2 } from "lucide-react";

interface EvidenceItem {
  id?: string;
  source_name: string;
  source_type: string;
  guideline_name: string;
  evidence_level: string;
  finding: string;
  recommendation: string;
  citation_url?: string;
}

export const ExplainabilitySection: React.FC = () => {
  const [evidenceList, setEvidenceList] = useState<EvidenceItem[]>([
    {
      source_name: "Clinical Pharmacogenetics Implementation Consortium (CPIC) & PharmGKB",
      source_type: "CPIC Guideline",
      guideline_name: "CPIC Guideline for CYP2D6 and Tamoxifen Therapy",
      evidence_level: "1A",
      finding: "CYP2D6 intermediate metabolizers taking strong CYP2D6 inhibitors exhibit significantly reduced active endoxifen plasma concentrations comparable to poor metabolizers.",
      recommendation: "Consider recommending alternative antidepressant with minimal CYP2D6 inhibition (e.g., Venlafaxine, Citalopram) or consulting oncology for alternative endocrine therapy.",
      citation_url: "https://cpicpgx.org/guidelines/guideline-for-tamoxifen-and-cyp2d6/"
    }
  ]);
  const [activeEvidenceIndex, setActiveEvidenceIndex] = useState<number>(0);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  useEffect(() => {
    const fetchEvidence = async () => {
      setIsLoading(true);
      try {
        const res = await fetch("/api/evidence?gene=CYP2D6&drug=Tamoxifen");
        if (res.ok) {
          const data = await res.json();
          if (data.evidence && data.evidence.length > 0) {
            setEvidenceList(data.evidence);
          }
        }
      } catch (err) {
        console.warn("Using baseline CPIC guideline:", err);
      } finally {
        setIsLoading(false);
      }
    };
    fetchEvidence();
  }, []);

  const activeEvidence = evidenceList[activeEvidenceIndex] || evidenceList[0];

  return (
    <section id="explainability" className="relative py-28 px-6 lg:px-14 border-b border-white/[0.06] bg-[#07090E]">
      <div className="max-w-6xl mx-auto">
        <SectionHeading
          badge="SECTION 07 // AUDITABLE EXPLAINABILITY"
          badgeColor="cyan"
          title={
            <>
              Don't just get a result. <br />
              <GlowText variant="cyan">Understand exactly why.</GlowText>
            </>
          }
          subtitle="Every risk alert generated by Curx is anchored in a transparent chain of evidence: from computed risk, to specific biological factor, to peer-reviewed guideline citation."
        />

        {/* 3-Step Explainability Chain */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-12 relative">
          {/* STEP 1: COMPUTED RESULT */}
          <div className="glass-panel rounded-2xl p-6 border border-curx-orange/30 flex flex-col justify-between relative">
            <div>
              <div className="flex items-center justify-between mb-4">
                <span className="px-2.5 py-1 rounded bg-curx-orange/15 border border-curx-orange/30 text-curx-orange font-mono text-[10px] font-bold tracking-widest uppercase">
                  STEP 01 // COMPUTED RESULT
                </span>
                <span className="w-2 h-2 rounded-full bg-curx-orange animate-pulse" />
              </div>

              <h4 className="font-display text-lg font-bold text-white mb-2">
                High Risk Warning Flagged
              </h4>
              <p className="text-xs text-slate-300 font-sans leading-relaxed mb-4">
                Deterministic engine flagged therapeutic failure risk for oncology adjuvant therapy.
              </p>

              <RiskBadge level="high" label="THERAPEUTIC INEFFICIENCY" size="md" />
            </div>

            <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-slate-400">
              Rule ID: PGX-CYP2D6-TAM-04
            </div>
          </div>

          {/* STEP 2: CONTRIBUTING FACTORS */}
          <div className="glass-panel rounded-2xl p-6 border border-curx-amber/30 flex flex-col justify-between relative">
            <div>
              <div className="flex items-center justify-between mb-4">
                <span className="px-2.5 py-1 rounded bg-curx-amber/15 border border-curx-amber/30 text-curx-amber font-mono text-[10px] font-bold tracking-widest uppercase">
                  STEP 02 // CONTRIBUTING MECHANISM
                </span>
                <span className="w-2 h-2 rounded-full bg-curx-amber" />
              </div>

              <h4 className="font-display text-lg font-bold text-white mb-2">
                Compound Phenoconversion
              </h4>
              <p className="text-xs text-slate-300 font-sans leading-relaxed">
                Intermediate metabolizer allele combined with strong enzyme inhibitor converts clearance profile to non-functioning phenotype.
              </p>

              <div className="mt-3 p-2.5 rounded bg-black/40 border border-white/[0.06] text-[11px] font-mono text-slate-300">
                CYP2D6 Activity Score: 0.5 → 0.0 (Suppressed)
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-slate-400">
              Factor Type: Pharmacokinetic Cross-Talk
            </div>
          </div>

          {/* STEP 3: EVIDENCE & GUIDELINE CITATION */}
          <div className="glass-panel rounded-2xl p-6 border border-curx-cyan/30 flex flex-col justify-between relative">
            <div>
              <div className="flex items-center justify-between mb-4">
                <span className="px-2.5 py-1 rounded bg-curx-cyan/15 border border-curx-cyan/30 text-curx-cyan font-mono text-[10px] font-bold tracking-widest uppercase">
                  STEP 03 // SOURCE CITATION
                </span>
                <span className="w-2 h-2 rounded-full bg-curx-cyan" />
              </div>

              <h4 className="font-display text-lg font-bold text-white mb-2">
                {activeEvidence.source_type}
              </h4>
              <p className="text-xs text-slate-300 font-sans leading-relaxed">
                {activeEvidence.guideline_name}
              </p>

              <div className="mt-3 p-2.5 rounded bg-curx-cyan/[0.06] border border-curx-cyan/30 text-[11px] font-mono text-curx-cyan font-semibold">
                Guideline Level: Level {activeEvidence.evidence_level} (Highest Recommendation)
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] font-mono text-curx-cyan flex items-center justify-between">
              <span>Source Linked ({evidenceList.length} Verified Sources)</span>
              <ShieldCheck className="w-3.5 h-3.5" />
            </div>
          </div>
        </div>

        {/* Evidence Card */}
        <div className="my-8">
          <EvidenceCard
            guideline={activeEvidence.guideline_name}
            source={activeEvidence.source_name}
            evidenceLevel={(activeEvidence.evidence_level as "1A" | "1B" | "2A" | "FDA Boxed" | "Clinical Rule") || "1A"}
            finding={activeEvidence.finding}
            recommendation={activeEvidence.recommendation}
          />
        </div>
      </div>
    </section>
  );
};
